name: Build, Push Docker and WhyLogs Profile

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/titanic-model:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/titanic-model:latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install whylogs
        run: pip install whylogs pandas

      - name: Run Titanic prediction and generate whylogs profile
        run: |
          mkdir output
          python scripts/generate_profile.py --input data/test.csv --output output/profile.bin

      - name: Upload whylogs profile artifact
        uses: actions/upload-artifact@v4
        with:
          name: whylogs-profile
          path: output/profile.bin
