name: Run Whylogs report

run-name: Run Whylogs report

on:
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-alpine
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python dummy.py
