name: Run Whylogs report

run-name: Run Whylogs report

on:
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-alpine
    steps:
      - run: python3 whylogs.py
